Create navbar to home page and style it
GSG-G11/Fitness-house pull request #109
Opened 2022-05-19 13:00 UTC by AhmedQeshta

## Create a navbar on the home page and style it

2022-05-21 10:16 UTC, AFahgan approved these changes

2022-05-21 11:23 UTC, LinaYahya requested changes

2022-05-21 11:23 UTC, LinaYahya commented on client/src/Components/Layout/Navbar/CardInputSearch.jsx
> +    const { data } = await axios({
change `handleSearch` only to `setSearch`,
then in separate `useEffect` send request whenever search value changes

2022-05-21 11:23 UTC, LinaYahya commented on client/src/Components/Layout/Navbar/index.jsx
> +                >
remove commented lines

2022-05-21 15:36 UTC, rawaneyad approved these changes
Great Job Ahmed 👍🏼

2022-05-22 07:37 UTC, LinaYahya approved these changes

2022-05-22 07:37 UTC, merged