Create Subscription Modal
GSG-G11/Fitness-house pull request #120
Opened 2022-05-22 16:43 UTC by AFahgan

![image](https://user-images.githubusercontent.com/44284483/169706248-6a07b4cb-5627-4772-ab8e-4429fa40053d.png)

2022-05-22 16:47 UTC, AhmedQeshta requested changes

2022-05-22 16:47 UTC, AhmedQeshta commented on client/src/Components/SingleGym/Modal/index.jsx
> +  const subscriptionSchema = Yup.object().shape({
this ` subscriptionSchema `, can put it  outside the component `Modal`

2022-05-22 17:16 UTC, AhmedQeshta approved these changes

2022-05-23 06:34 UTC, LinaYahya requested changes
Good Job Ayman, try to complete it to send the request completely,
And also we need to display six and one month prices in the gum card itself, and in the modal

2022-05-23 06:34 UTC, LinaYahya commented on client/src/Components/SingleGym/Modal/index.jsx
> +  phone: Yup.string()
```suggestion
  userPhone: Yup.string()
```
as it stored in the database

2022-05-23 06:34 UTC, LinaYahya commented on client/src/Components/SingleGym/Modal/index.jsx
> +  subscription: Yup.string().required("حقل الاشتراك مطلوب"),
```suggestion
  type: Yup.string().required("حقل الاشتراك مطلوب"),
```

2022-05-23 06:34 UTC, LinaYahya commented on client/src/Components/SingleGym/Modal/index.jsx
> +              onClick={handleClose}
```suggestion
```
this is the form submit button, so on submit will control this button action

2022-05-23 12:07 UTC, AhmedQeshta approved these changes
Great work Ayman!

2022-05-24 06:01 UTC, rawaneyad approved these changes
Great Job Ayman 👍🏼

2022-05-24 06:53 UTC, LinaYahya approved these changes

2022-05-24 06:53 UTC, merged