General points to fix
GSG-G11/Fitness-house pull request #145
Opened 2022-05-25 11:50 UTC by AFahgan

2022-05-25 11:54 UTC, AhmedQeshta approved these changes

2022-05-25 12:52 UTC, LinaYahya requested changes

2022-05-25 12:52 UTC, LinaYahya commented on client/src/Components/SearchPage/CardResultFilter/Card.jsx
> +        {images.length && <img alt="complex" src={images[0].pathUrl} />}
I think it's better to render logo if images length equals zero
```suggestion
        {images.length ? <img alt="complex" src={images[0].pathUrl} /> : <img alt="complex" src={logo // or whatever} />  }
```

2022-05-26 08:07 UTC, rawaneyad approved these changes
Good Job 👍🏼

2022-05-26 08:23 UTC, LinaYahya requested changes

2022-05-26 08:23 UTC, LinaYahya commented on client/src/Components/SearchPage/FilterSide/index.jsx
> +console.log(gymsFeatures, genders, cities);
```suggestion
```

2022-05-26 08:35 UTC, LinaYahya approved these changes

2022-05-26 08:36 UTC, merged