Create gym and image model in server
GSG-G11/Fitness-house pull request #18
Opened 2022-04-28 13:18 UTC by AhmedQeshta

## Create gym and image model in server

Tables

![image](https://user-images.githubusercontent.com/38624002/165761067-80f62ba8-aebb-4276-9bc3-2b12a4fdf326.png)

2022-04-28 13:45 UTC, AFahgan commented
Great Job Ahmed

2022-04-28 14:09 UTC, rawaneyad approved these changes
Well Done Ahmed 👍🏼

2022-04-29 11:29 UTC, LinaYahya requested changes

2022-04-29 11:29 UTC, LinaYahya commented on server/database/models/gyms.ts
> +    type: DataTypes.JSONB,
I think it would be better to have a type Array
```suggestion
    type: DataTypes.ARRAY(DataTypes.STRING),
```

2022-04-29 11:42 UTC, LinaYahya approved these changes

2022-04-29 11:42 UTC, merged