create subscription and reviews model
GSG-G11/Fitness-house pull request #21
Opened 2022-04-28 21:43 UTC by rawaneyad

## Create subscription and reviews model
Tables
![db](https://user-images.githubusercontent.com/57105261/165850089-a115ec50-e946-451f-b243-46ed67224db8.png)

- [ ] Create subscription model
- [ ] Create reviews model
- [ ] Update index

2022-04-28 22:08 UTC, AhmedQeshta requested changes

2022-04-28 22:08 UTC, AhmedQeshta commented on server/database/models/subscription.ts
> +  created_at: {
Must Remove  create_at, because sequelize create it by default

2022-04-29 11:40 UTC, LinaYahya requested changes

2022-04-29 11:40 UTC, LinaYahya commented on server/database/models/subscription.ts
> +const Subscription = sequelize.define('Subscription', {
```suggestion
const Subscription = sequelize.define('subscriptions', {
```

2022-04-29 11:40 UTC, LinaYahya commented on server/database/models/subscription.ts
> +    allowNull: false,
```suggestion
    allowNull: false,
     values: ['one', 'six'],
```
I would prefer to specify values either to be six for six months subscription or one

2022-04-29 11:40 UTC, LinaYahya commented on server/database/models/reviews.ts
> +const Reviews = sequelize.define('Reviews', {
```suggestion
const Reviews = sequelize.define('reviews', {
```

2022-04-29 11:42 UTC, AhmedQeshta approved these changes

2022-04-29 12:44 UTC, LinaYahya approved these changes

2022-04-29 12:45 UTC, merged