Create fake data
GSG-G11/Fitness-house pull request #23
Opened 2022-04-29 15:24 UTC by AhmedQeshta

## Create fake data 

- Create fake data for users
- Create fake data for gyms
- Create fake data for reviews
- Create fake data for subscriptions

-------------------------------
and Create Files For static data ( cities and features )

2022-04-29 15:34 UTC, rawaneyad approved these changes
Good job Ahmed 👍🏼

2022-05-01 11:59 UTC, LinaYahya requested changes

2022-05-01 11:59 UTC, LinaYahya commented on server/database/config/connection.ts
> -sequelize.sync();
We need this for both production and development, But maybe we can wrap it in a condition!
MAYBE in the build script, you can add environment variable like
DB_BUILD=true
and here you can sync sequelize when DB_BUILD equals false

2022-05-05 09:27 UTC, LinaYahya approved these changes

2022-05-05 09:28 UTC, merged