Create api for getting top gyms
GSG-G11/Fitness-house pull request #32
Opened 2022-05-05 13:56 UTC by AhmedQeshta

- Create route `/api/v1/gyms/top`
- Create controller
- Handle data Form the database

and the response like this 

```JSON
{
    "status": 200,
    "gyms": [
        {
            "id": "..",
            "gymName": "..",
            "logo": "...",
            "city": "...",
            "description": "...",
            "features": ["...","..."],
            "reviews": "...",
            "image": "...."
        },
           {
            "id": "..",
            "gymName": "..",
            "logo": "...",
            "city": "...",
            "description": "...",
            "features": ["...","..."],
            "reviews": "...",
            "image": "...."
        },
    {
            "id": "..",
            "gymName": "..",
            "logo": "...",
            "city": "...",
            "description": "...",
            "features": ["...","..."],
            "reviews": "...",
            "image": "...."
        }

  ]
}
```

2022-05-05 19:15 UTC, rawaneyad approved these changes
Good job Ahmed 👌🏼👍🏼

2022-05-05 19:35 UTC, AFahgan approved these changes
Great job Ahmed

2022-05-06 22:18 UTC, LinaYahya requested changes

2022-05-06 22:18 UTC, LinaYahya commented on server/controllers/gyms/getTopGyms.ts
> +      order: [Sequelize.literal('avg_rate')],
here you 're not ordering by descending rate
```suggestion
      order: [[Sequelize.literal('avg_rate'), 'DESC']],
```

2022-05-06 22:55 UTC, AhmedQeshta commented on server/database/models/index.ts
> +  foreignKey: 'gym_id',
because when using `gymId `, a query tells me can not find a column like it.
but when use this way works correctly

2022-05-07 11:26 UTC, AhmedQeshta commented on server/database/models/index.ts
> +  foreignKey: 'gym_id',
I solve this issue

2022-05-07 12:32 UTC, LinaYahya requested changes

2022-05-07 12:32 UTC, LinaYahya commented on server/app.ts
> +import morgan from 'morgan';
Heroku won't be able to import morgan as a dev dependency, So try to import it conditionally

2022-05-07 13:06 UTC, LinaYahya approved these changes

2022-05-07 13:06 UTC, merged