40 create api for getting gym data
GSG-G11/Fitness-house pull request #42
Opened 2022-05-08 10:33 UTC by rawaneyad

-  Create route /api/v1/gyms/:gymID
-  Create controller
-  Handle data Form the database

and the response like this
```
{
  "Gymdata": [
    {
      "id": 1,
      "gymName": "نادي فريندز للياقة البدنية",
      "logo": "https://bit.ly/3yij5Wb",
      "city": "غزة",
      "description": ".نادي رياضي يحتوي على ملعب وميدان تنافسي وملعب رياضي, أوقات الدوام من 8-11 صباحا ومن 13-17 مساء",
      "features": [
        "ميدان تنافسي",
        "ملعب رياضي"
      ],
      "images": [
        {
          "pathUrl": "https://bit.ly/39s08Wv"
        },
        {
          "pathUrl": "https://bit.ly/3kpe2e9"
        },
        {
          "pathUrl": "https://bit.ly/3LxTj3Y"
        }
      ],
      "reviews": [
        {
          "rate": 2,
          "description": "للأسف كانت تجربة سيئ جدأ , لا أنصح به ",
          "createdAt": "2022-05-08T09:23:16.894Z",
          "userId": 3,
          "user": {
            "username": "حسن عبدالله",
            "avatar": "https://bit.ly/38CU9xq"
          }
        },
        {
          "rate": 1,
          "description": "للأسف كانت تجربة سيئ جدأ , لا أنصح به ",
          "createdAt": "2022-05-08T09:23:16.894Z",
          "userId": 1,
          "user": {
            "username": "محمود علي",
            "avatar": "https://bit.ly/37THiXV"
          }
        },
        {
          "rate": 3,
          "description": "للأسف كانت تجربة سيئ جدأ , لا أنصح به ",
          "createdAt": "2022-05-08T09:23:16.894Z",
          "userId": 2,
          "user": {
            "username": "علي محمود",
            "avatar": "https://bit.ly/3EYZU4G"
          }
        }
      ]
    }
  ]
}
```

2022-05-08 10:35 UTC, AhmedQeshta approved these changes

2022-05-08 11:12 UTC, LinaYahya requested changes

2022-05-08 11:12 UTC, LinaYahya commented on server/controllers/gym/getGym.ts
> +    const { id } = req.params;
validate params to be a number using `hapi/joi` before running database find query

2022-05-08 11:12 UTC, LinaYahya commented on server/controllers/gym/getGym.ts
> +    const Gymdata = await Gym.findAll({
```suggestion
    const gymData = await Gym.findAll({
```
Follow camelCase convention naming your vars

2022-05-08 11:12 UTC, LinaYahya commented on server/controllers/gym/getGym.ts
> +        ['gym_name', 'gymName'],
change it in the Gym model itself

2022-05-08 11:12 UTC, LinaYahya commented on server/routes/gyms.ts
> +gyms.get('/top', getAllGyms);
`getTopGyms` more descriptive I think

2022-05-08 11:12 UTC, LinaYahya commented on test/routes.test.ts
> +  test('Gyms - GET - /api/v1/gyms/:id - ', async () => {
add  tests to test Both `/api/v1/gyms/gggggggg` and `/api/v1/gyms/50`

2022-05-08 13:48 UTC, AFahgan approved these changes
Great Job 
Conflict resolved.

2022-05-09 09:08 UTC, LinaYahya approved these changes

2022-05-09 09:09 UTC, merged