Create Side Filter Component
GSG-G11/Fitness-house pull request #61
Opened 2022-05-11 13:08 UTC by AFahgan

![image](https://user-images.githubusercontent.com/44284483/167862057-1ccebfc0-5d4e-48be-9f97-3894b42ffc18.png)

2022-05-11 13:09 UTC, AhmedQeshta approved these changes

2022-05-11 13:31 UTC, rawaneyad approved these changes
Great Job Ayman 👍🏼

2022-05-11 17:23 UTC, LinaYahya requested changes

2022-05-11 17:23 UTC, LinaYahya commented on client/src/Components/FilterSide/index.jsx
> +  const [inputfilter, setInputfilter] = React.useState(initilstate);
What you are doing here that you share the same state for all your inputs, So when I type something  in name input I change the state for the all inputs I have, Which led to unnecessary rendering,
So try to create a separate state for all your inputs

2022-05-12 10:33 UTC, LinaYahya approved these changes

2022-05-12 10:34 UTC, merged