Frontend create a card for rendering the result of filtering
GSG-G11/Fitness-house pull request #62
Opened 2022-05-11 18:05 UTC by AhmedQeshta

### Frontend creates a card for rendering the result of filtering

![image](https://user-images.githubusercontent.com/38624002/167916783-2cc3a7e6-c715-4aca-a04a-d3e05fc707b9.png)

2022-05-11 18:22 UTC, rawaneyad approved these changes
Great Job Ahmed👍🏼

2022-05-12 06:09 UTC, LinaYahya requested changes

2022-05-12 06:09 UTC, LinaYahya commented on client/src/Components/SearchPageComponents/CardResultFilter/Card.jsx
> +      <div className="body__card">
try to add more padding to card body

2022-05-12 06:09 UTC, LinaYahya commented on client/src/Components/SearchPageComponents/CardResultFilter/Card.jsx
> +            <Button variant="contained">احجز موعد</Button>
No need to have a button here,
Just create a div or span and customize style to fit your design

2022-05-12 07:20 UTC, LinaYahya approved these changes

2022-05-12 07:22 UTC, AFahgan approved these changes

2022-05-12 07:22 UTC, merged