style: fix style
GSG-G11/Fitness-house pull request #67
Opened 2022-05-12 11:46 UTC by AFahgan

2022-05-13 14:47 UTC, AhmedQeshta requested changes

2022-05-13 14:48 UTC, AhmedQeshta commented on client/src/Components/SearchPageComponents/CardResultFilter/index.jsx
> +          count={10}
```suggestion
          count={filter.length} // or **arr length**
```

2022-05-13 14:50 UTC, AhmedQeshta commented on client/src/Store/Services/gyms.js
> +      query: (name) => `/filter?name=${name}`,
```suggestion
      query: (name) => `/filter?name=${name}&....`, // you must complete filter query
```

2022-05-14 15:18 UTC, AhmedQeshta approved these changes

2022-05-14 16:07 UTC, rawaneyad approved these changes
Great Job Ayman 👍🏼

2022-05-15 11:10 UTC, LinaYahya requested changes

2022-05-15 11:10 UTC, LinaYahya commented on client/src/Components/SearchPageComponents/Filter/index.jsx
> +
add a state for pages
```suggestion
  const [page, setPage] = useState(0)
```
and then set count as `Math.ceil(page/3)`

2022-05-15 11:10 UTC, LinaYahya commented on client/src/Components/SearchPageComponents/Filter/index.jsx
> +  }, []);
```suggestion

```

2022-05-15 17:27 UTC, LinaYahya approved these changes

2022-05-15 17:29 UTC, merged