Create user/gym auth
GSG-G11/Fitness-house pull request #68
Opened 2022-05-12 15:26 UTC by rawaneyad

- [x] create verfiy and sign function.
- [x] create check middelware checkGymAuth.
- [x] create check middelware  checkUserAuth.

2022-05-12 16:18 UTC, AhmedQeshta approved these changes
Good Job Rawan 👩🏻‍💻

2022-05-12 21:00 UTC, LinaYahya requested changes

2022-05-12 21:08 UTC, LinaYahya requested changes

2022-05-12 21:08 UTC, LinaYahya commented on server/utils/jwt.ts
> +    sign(payload, process.env.JWT_SECRET!, OPTIONS, (err, encodePayload) => {
not sure what `!` in JWT_SECRET means

2022-05-14 06:57 UTC, LinaYahya approved these changes

2022-05-14 17:19 UTC, AFahgan approved these changes

2022-05-15 06:07 UTC, merged