Start creating step contact information
GSG-G11/Fitness-house pull request #77
Opened 2022-05-15 13:38 UTC by AhmedQeshta

## Start creating step contact information

2022-05-15 17:47 UTC, LinaYahya requested changes

2022-05-15 17:47 UTC, LinaYahya commented on client/src/Components/RegisterPageComponents/Stepper/BodyStepper.jsx
> +    phone: Yup.string()
remove schema outside component

2022-05-15 17:47 UTC, LinaYahya commented on client/src/Components/RegisterPageComponents/Stepper/Steps/StepThreeComponent.jsx
> +  console.log(contactForm.values);
```suggestion
```

2022-05-15 17:47 UTC, LinaYahya commented on client/src/Components/RegisterPageComponents/Stepper/BodyStepper.jsx
> +      .max(10, "الرقم يجب أن  لا يكون 10 أرقام")
```suggestion
     .length(10, message)
```

2022-05-16 06:08 UTC, LinaYahya approved these changes

2022-05-16 06:16 UTC, AFahgan approved these changes
Great

2022-05-16 06:36 UTC, rawaneyad approved these changes
Good Job 👍🏼

2022-05-16 06:36 UTC, merged