Create Step Three Form register
GSG-G11/Fitness-house pull request #82
Opened 2022-05-16 09:02 UTC by AFahgan

![image](https://user-images.githubusercontent.com/44284483/168557539-81ed412f-7a37-40d4-b50e-1d6df480a549.png)

2022-05-16 14:36 UTC, AhmedQeshta requested changes

2022-05-16 14:36 UTC, AhmedQeshta commented on client/src/Components/RegisterPageComponents/Stepper/Steps/gymdata.jsx
> +const gymData = {
you can use a file JSON form `client\src\Services\Cities.json` , and and import it like this 
```js
import * as Cities from "../../../../Services/Cities.json";

const { cities } = Cities;
```
and add other like above

2022-05-16 17:26 UTC, LinaYahya requested changes

2022-05-16 17:26 UTC, LinaYahya commented on client/src/Components/RegisterPageComponents/Stepper/BodyStepper.jsx
> +  const thirfForm = useFormik({
```suggestion
  const detailsForm = useFormik({
```

2022-05-16 17:26 UTC, LinaYahya commented on client/src/Components/RegisterPageComponents/Stepper/BodyStepper.jsx
> +      StepComponent = <StepThreeComponent thirfForm={thirfForm} />;
```suggestion
      StepComponent = <StepThreeComponent detailsForm={detailsForm} />;
```

2022-05-16 17:26 UTC, LinaYahya commented on client/src/Components/RegisterPageComponents/Stepper/BodyStepper.jsx
> +  sixMonthPrice: Yup.number().moreThan(1, "قيمة اشتراك الستة أشهر مطلوب"),
remove required from textField and add your validation here
```suggestion
  sixMonthPrice: Yup.number().moreThan(1, "قيمة اشتراك الستة أشهر مطلوب").required("msg"),
,
```
the same for month price validation

2022-05-16 17:26 UTC, LinaYahya commented on client/src/Components/RegisterPageComponents/Stepper/Steps/StepThreeComponent.jsx
> +          required
```suggestion
          
```

2022-05-16 17:26 UTC, LinaYahya commented on client/src/Components/RegisterPageComponents/Stepper/Steps/StepThreeComponent.jsx
> +          required
```suggestion
```

2022-05-16 18:40 UTC, LinaYahya approved these changes

2022-05-16 19:41 UTC, rawaneyad approved these changes
Great Job Ayman 👍🏼

2022-05-17 06:13 UTC, AhmedQeshta approved these changes

2022-05-17 06:22 UTC, merged