Front end Create layout dashboard
GSG-G11/Fitness-house pull request #83
Opened 2022-05-16 10:03 UTC by AhmedQeshta

![image](https://user-images.githubusercontent.com/38624002/168569021-78315ad1-f261-4019-87bc-a9b4d1e275d9.png)

2022-05-16 15:38 UTC, rawaneyad approved these changes
Great Job Ahmed 👍🏼

2022-05-16 17:47 UTC, LinaYahya requested changes

2022-05-16 17:47 UTC, LinaYahya commented on client/src/App.js
>          <Route path="gym" element={<GymPage />} />
```suggestion
```
No need for index and same path route

2022-05-16 17:47 UTC, LinaYahya commented on client/src/Components/DashboardPageComponents/SideBar/index.jsx
> +    link: "gym/subscribers ",
change to follow changes on routes naming

2022-05-17 06:05 UTC, LinaYahya approved these changes

2022-05-17 06:09 UTC, AFahgan approved these changes

2022-05-17 06:10 UTC, merged