feat: add login component and use formik
GSG-G11/Fitness-house pull request #97
Opened 2022-05-17 11:35 UTC by rawaneyad

![login](https://user-images.githubusercontent.com/57105261/168801827-ecb0e612-540b-4ecc-851f-ef394ade95a3.png)

2022-05-17 15:47 UTC, AhmedQeshta approved these changes
🌀 Greate Job Rawan

2022-05-18 06:53 UTC, AFahgan approved these changes

2022-05-18 09:02 UTC, LinaYahya requested changes

2022-05-18 09:02 UTC, LinaYahya commented on client/src/Components/LoginPage/index.jsx
> +        error={!!loginForm.errors.email}
```suggestion
        error={!!loginForm.errors.email}
        autoComplete="email"
```

2022-05-18 09:02 UTC, LinaYahya commented on client/src/Components/LoginPage/index.jsx
> +        autoComplete="new-password"
```suggestion
        autoComplete="current-password"
```

2022-05-18 10:19 UTC, LinaYahya approved these changes

2022-05-18 10:20 UTC, merged